### ISSUE TITLE
Automatic conversion of comparison operator.

### ISSUE THREAD

**Issue by geekypandey** [carbon-app/carbon#1029]
**Describe the bug**
Automatic conversion of *>=* to *&ge;*

**To Reproduce**

1. Go [here](https://carbon.now.sh)
2. Type >=
3. See error

**Expected behavior**
The  >= should not be converted to &ge;

**Screenshots**

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Linux
- Browser [e.g. chrome, safari]: Chrome
-

<details>
  <summary>Code Snippet (If Applicable)</summary>
  <pre>
  
  </pre>
</details>

**Comment by manishsundriyal** [comment]
Actually this depends on the font that you use.
In my opinion, it should only be dependent on the font style.
Try this in font: "Fira Code"

<img width="881" alt="Screenshot 2020-06-14 at 9 37 18 PM" src="https://user-images.githubusercontent.com/24211507/84598279-41718c80-ae87-11ea-8607-ae373eb03378.png">

**Comment by mfix22** [comment]
@geekypandey this is actually intentional. It is also the reason "Hack" is our default font, as it does not use "[ligatures](https://en.wikipedia.org/wiki/Orthographic_ligature)".

If you would like to use a different font style, you can actually upload your own here:

<img width="973" alt="Screenshot 2020-06-14 12 24 49" src="https://user-images.githubusercontent.com/8397708/84602151-14e35380-ae3a-11ea-8065-e646c47ed652.png">

**Comment by geekypandey** [comment]
oh okay. That is understandable. Thank you.
