### ISSUE TITLE
Syntax highlight for format strings disappears when exporting to PNG

### ISSUE THREAD

**Issue by unililium** [carbon-app/carbon#1064]
**Description**
Lines containing a format string with width specification (e.g. "%2d") makes the syntax highlight for that entire line to disappear when exporting to PNG. It is caused by the expansion in the URL of said characters.
Exporting to SVG works fine.

**Screenshots**
When exported to PNG:
![carbon](https://user-images.githubusercontent.com/3117172/89279977-4f9e8680-d648-11ea-9561-196da6af91bf.png)
expected:
![expected](https://user-images.githubusercontent.com/3117172/89279961-4a413c00-d648-11ea-8833-1ee331d593ba.png)

<details>
  <summary>URL</summary>
  <pre>
https://carbon.now.sh/?bg=rgba(171%2C%20184%2C%20195%2C%201)&t=one-dark&wt=none&l=text%2Fx-csrc&ds=true&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=56px&ph=56px&ln=false&fl=1&fm=Hack&fs=14px&lh=133%25&si=false&es=1x&wm=false&code=int%2520main()%2520%257B%250A%2509printf(%2522%252510d%255Cn%2522%252C%252012345)%253B%2520char%2520s%255B1%255D%253D%2522%2522%253B%250A%2509printf(%2522format%2520string%2520%2525s%2522%252C%2520s)%253B%250A%257D
  </pre>
</details>

**Comment by qw-in** [comment]
Spent a few minutes looking into this out of curiosity and here is what I have found:

1. This is caused by the following snippet of code
    https://github.com/carbon-app/carbon/blob/7adb50753e090d3873049c261f95191c6fb979f2/components/Editor.js#L134-L143
1. This code calls `encodeURIComponent` on `%10`
1. This means the `innerText` is set to `"    printf("%2510d\n", 12345); char s[1]="";"`
1. The entire line loses highlighting - adding a breakpoint on `L144` confirms this visually
