### ISSUE TITLE
Include Recursive font

### ISSUE THREAD

**Issue by javlaks** [carbon-app/carbon#1068]
Is it possible to include the new font Recursive? This new font is great and open source. It has many feaures and I think is a great font. I'm using it in my local environment with Visual Studio Code and it looks amazing.

![image](https://user-images.githubusercontent.com/513351/89746514-a4defb80-da7f-11ea-90b0-2671c1ae3b54.png)

You can find it here -> [Recursive Repository](https://github.com/arrowtype/recursive/)

![image](https://user-images.githubusercontent.com/513351/89746402-12d6f300-da7f-11ea-9078-9cf0df55f589.png)

**Comment by mfix22** [comment]
Hey @javlaks  thank you for proposing this new Font. Since Carbon implemented custom fonts, we are actually no longer implementing new fonts, except for in extenuating circumstances. 

You can use your own custom font in the Font settings here:
<img width="967" alt="Screen Shot 2020-08-10 at 10 05 06 PM" src="https://user-images.githubusercontent.com/8397708/89859322-96fbaa00-db55-11ea-9e9b-d97973d6cae6.png">

If this particular Font faces drastically  increases in popularity in the future, we will definitely reconsider. 

Sorry about the extra effort—would be happy to except other contributions from you in the future.
