### ISSUE TITLE
Option to disable font ligatures

### ISSUE THREAD

**Issue by JaKXz** [carbon-app/carbon#1088]
Hi! Big fan of carbon for showing off snippets to friends and keeping some for myself :) 

**Is your feature request related to a problem? Please describe.**
This was sort of reported in #1029, but I understand it's a feature of the different fonts. However, I love using Fira Code in my local editor but I have the option to support ligatures turned off. 

**Describe the solution you'd like**
I want the option to disable font ligatures, no matter the font. This also makes it easier when teaching people and what not.

**Describe alternatives you've considered**
I can certainly live without this and just use fonts that don't have ligatures - just wanted to ask if it would be something that would be considered or merged if a PR was made :) feel free to close this issue if not!

**Comment by mfix22** [comment]
Hey @JaKXz thanks the kind words, and for posting this issue. 

Since Carbon implemented custom fonts, we are actually no longer implementing new fonts, except for in extenuating circumstances. 

You can use your own custom font (Fira without ligatures) in the Font settings here:
<img width="967" alt="Screen Shot 2020-08-10 at 10 05 06 PM" src="https://user-images.githubusercontent.com/8397708/89859322-96fbaa00-db55-11ea-9e9b-d97973d6cae6.png">

If we hear more cases of wanting this in the future, we will definitely reconsider.
