### ISSUE TITLE
📝 Emoji Support 🚀

### ISSUE THREAD

**Issue by shaonkabir8** [carbon-app/carbon#1120]
Hi 👋 
Hopefully many of us need to use `emoji` while creating beautiful `carbon` image. And It doesn't need to be explained why we use `emoji` 😎 

**Features we can add:**

- [ ]  Add `Emoji`  List `Tab` besides our `Menu`.

Thanks ❤️ 
\- Shaon Kabir

**Comment by mfix22** [comment]
@shaonkabir8 emojis should work by default in Carbon! Are the currently not working for you? 

Here is an example: 
![carbon (15)](https://user-images.githubusercontent.com/8397708/97381805-195b5680-1887-11eb-8f26-521cadbc87cd.png)

**Comment by shaonkabir8** [comment]
Sorry for misunderstanding. you don't get my point actually.

I'll explain it in details soon. 
thanks

**Comment by mfix22** [comment]
Do you mean you would like an Emoji menu? If that is the case, Carbon doesn't need to support it, since Emoji is built into most operating system keyboards. 🙂 

On mac, you can open this menu up by clicking <kbd>Control+Command+Space</kbd>

If your operating system doesn't support this, you can always use a site like this: https://emojipedia.org

**Comment by shaonkabir8** [comment]
Thanks a lot.  You save my day.🙏
I just wanna explain it. 🖐

Take my love mate. 😘

**Comment by mfix22** [comment]
🖤 💛
