### ISSUE TITLE
Font IBM Plex Mono is in italic

### ISSUE THREAD

**Issue by vtmx** [carbon-app/carbon#1177]
<img src="https://i.imgur.com/gQO3Hto.png">

**Comment by questionlp** [comment]
It looks like the `@font-face` referenced in `components/style/Font.js` needs to be replaced with something like the following:

```
@font-face {
  font-family: 'IBM Plex Mono';
  font-display: swap;
  font-weight: 500;
  src: local('IBM Plex Mono Medium'), local('IBMPlexMono-Medium'),
    url(https://fonts.gstatic.com/s/ibmplexmono/v6/-F6qfjptAgt5VM-kVkqdyU8n3twJwl5FgsAXHNlYzg.woff2) format('woff2');
}
```

**Comment by adghayes** [comment]
In #324, IBM Plex Mono was added intentionally as italic. In #394, @mfix22 suggested using IBM Plex Mono when an italic font is needed. It's possible people are using the font as their only built-in italic option.

@mfix22 seems like there are a few ways of addressing, if we settle on which is best I can make a PR:
1. Rename existing `@font-face` to `IBM Plex Mono Italic` in UI. Would remove the font on existing configs
2. Add an additional font so there's one italic and one normal. Would de-italicize the font on existing configs
3. Add a general italic option. Seems like this was a no in the past

@questionlp, I double-checked locally and your replacement does make the font non-italic (option 1), would just combine new and old for option 2

**Comment by questionlp** [comment]
Without knowing the history of the decision and using IBM Plex Mono as my default font in my IDE and terminals, it's a bit odd that it was the only font that was italicized and I found this issue. My vote would be for option 2.

**Comment by adghayes** [comment]
I had a chance to discuss offline with @mfix22. We decided it makes best sense to switch from italic to regular rather than have italic or have both fonts. People can still create italic screenshots by selecting the text and clicking the _I_ button. It doesn't look quite the same because the browser approximates italics rather than having italic-specific glyphs. We _could_ add italic glyphs by adding another `@font-face` definition, but it raises the question of whether we should do it for all fonts - in any case a separate issue and PR.

Made a PR with the change to Regular (rather than Medium).
