### ISSUE TITLE
Fortran syntax highlighting

### ISSUE THREAD

**Issue by zmoon** [carbon-app/carbon#1308]
**Describe the bug**
Carbon purports to support Fortran syntax highlighting, but it seems to not work as well as it should (given that it is using Highlight.js; https://github.com/Beliavsky/FortranTip/issues/24).

**To Reproduce**
See https://twitter.com/fortrantip/status/1477632693617799169/photo/1

**Expected behavior**
For the example above, https://github.com/highlightjs/highlight.js/issues/3450#issuecomment-1004361354 (see the Highlight.js response).

**Comment by dcshzj** [comment]
I found that this bug arises from CodeMirror, and I have submitted an upstream PR to resolve it. I am not sure if there are additional changes to be made on carbon.

**Comment by dcshzj** [comment]
The bug seems to be fixed with https://github.com/codemirror/CodeMirror/commit/191ae470666f877d6598dce020e8bff2823a216f.

This is the output for the version that carbon is using (5.64.0):
![carbon](https://user-images.githubusercontent.com/27919917/150085183-afff87df-c3e1-46c2-9db4-3fd88ceafd5d.png)

This is the output with the commit above:
![carbon (1)](https://user-images.githubusercontent.com/27919917/150085208-4a482711-4ea0-4c74-9004-ad21966d9f26.png)

Once the commit is released in the codemirror package, I'll send a PR to upgrade it for carbon.
