### ISSUE TITLE
Copy Plain URL doesn't copy anything

### ISSUE THREAD

**Issue by OnkelTem** [carbon-app/carbon#1379]
**Describe the bug**
Copying "Plain URL" doesn't work.

**To Reproduce**

1. Open https://carbon.now.sh/
2. Select the "Plain URL" item from the copy menu:

![image](https://user-images.githubusercontent.com/114060/169711470-bbee7075-122b-4be7-995b-ee850ca4d39c.png)

3. Open a new tab and paste the URL. It pastes just the site's root URL: https://carbon.now.sh/

**Expected behavior**
A link to the snippet would get copied.

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Linux
- Browser [e.g. Chrome, Safari, Firefox]: Chrome 100

**Comment by mfix22** [comment]
Does your browser have access to the clipboard? This works great on all browsers I have access to.

**Comment by OnkelTem** [comment]
Of course it has. It just doesn't copy anything. I can make a video.

**Comment by mfix22** [comment]
Thanks for the helpful reproduction video @OnkelTem! This should be an easy fix (I imagine you would be able to fix it yourself if you are interested).

**Comment by agilityhawk** [comment]
Hello. I was looking to pick this up and have been able to reproduce it on the prod site (thanks to the vid by @OnkelTem). However, in order to reproduce this locally and confirm my fix, I wanted to go through the flow and receive the API response that saves the snippet but am unable to locate the API/server-side code were this response is supposed to come from.

Since I was unable to find it in this code, I'm assuming that API and backend code for this is somewhere else? 
@mfix22 - Could please provide further insights into this assumption please? 

Additionally, I was wondering if we could add a local/placeholder .env file that just lists down all the ENV variables that are consumed by this code, incase we wanted to set them up locally as well?

Thanks in advance!
