### ISSUE TITLE
Carbon turns `!=` into `≠`

### ISSUE THREAD

**Issue by JakobDev** [carbon-app/carbon#1524]
**Describe the bug**
Carbon turns `!=` into `≠`.

**To Reproduce**
Select Go as Language and paste this code:
```go
if a != b {
  return false
}

```
1. Go to '…'
2. Click on '…'
3. See error

**Expected behavior**
`!=` should be in the code and not  `≠`..
It's in the code I pasted.  `≠` is not even valid Go code.
At least there should be an Option to turn this auto replacement off.

**Screenshots**
![Unbenannt](https://github.com/carbon-app/carbon/assets/15185051/8cb3390e-dd84-4b17-a63d-27c16d2b09bb)

**Info (please complete the following information):**

- OS: Linux
- Browser Firefox:
- Carbon URL: https://carbon.now.sh/?bg=rgba%28248%2C231%2C28%2C0%29&t=blackboard&wt=none&l=text%2Fx-go&width=1280&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=true&fl=1&fm=Fira+Code&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=if%2520a%2520%21%253D%2520b%2520%257B%250A%2520%2520return%2520false%250A%257D

**Comment by themowski** [comment]
The default font is Fira Code with ligature support enabled. Switch to a font that does not use ligatures to resolve this. For example, using Inconsolata instead:
https://carbon.now.sh/?bg=rgba%28248%2C231%2C28%2C0%29&t=blackboard&wt=none&l=text%2Fx-go&width=1280&ds=false&dsyoff=20px&dsblur=68px&wc=true&wa=true&pv=0px&ph=0px&ln=true&fl=1&fm=Inconsolata&fs=14px&lh=152%25&si=false&es=2x&wm=false&code=if%2520a%2520%21%253D%2520b%2520%257B%250A%2520%2520return%2520false%250A%257D

Adding support for disabling ligatures is was requested in #1088 and the resolution there was no action, since you can upload your own font without ligatures and use that.

**Comment by mfix22** [comment]
Thanks @themowski! This is intentional.
