### ISSUE TITLE
Code does not contain GitHub (and Firebase) intergration

### ISSUE THREAD

**Issue by StefMa** [carbon-app/carbon#841]
Hey guys 👋 

first of all thanks for this nice little app.
Its really awesome.

You introduced carbon 4.0 with the GitHub integration.
Meaning we can sign in with our GitHub account and save our stuff in somewhere in the Firebase universe.

Because I plan something similar in one of my projects I tried to figgured out how do you have implemented this feature by browser through the source code.
Unfortunately there isn't something (or I'm to dumb to find it :D).
I've also checked out the repo and build it to now. There is also no GitHub integration :(

Anyways.
I'm totally fine with it if you don't want to share it. I even accept if you don't want to explain it.
But would you so good to share the general workflow here? 🙏 😇 

That would be awesome. Thank you 👌 

(I'm also fine if you just close this issue 😂 )

**Comment by mfix22** [comment]
Hey @StefMa,
Thanks for the note! You are totally right — it is missing from the open source repo. I have not yet decided if I am going to open source that part of the app yet, in order to lower security risks (or at a minimum make them less transparent). 

The other reason, is I need to improve the dev mode when running the app locally with/without firebase before merging it in here 👌 

However, this is the second day of those features in production — once more people try them out and we are more confident with the implementation, I would _love_ to open merge those changes in ❤️

**Comment by mfix22** [comment]
`4.0.0` code merged in 👍

**Comment by StefMa** [comment]
Thank you ☺
