### ISSUE TITLE
Enable header or footer text outside the code screenshot

### ISSUE THREAD

**Issue by faraweilyas** [carbon-app/carbon#937]
> Carbon does the job and it's a great tool, it'd be nice to have a feature that lets you type a header or footer text outside the code screenshot, more like around the background image or color, cheers!

**Comment by mfix22** [comment]
Thanks for the kind words, @faraweilyas, and for posting this idea! 

Since we already have snippet titles (as you can see in the image), I am hesitant to add other header text. 

![carbon (1)](https://user-images.githubusercontent.com/8397708/73129688-439d8200-3f9e-11ea-9f39-e545fc612211.png)

We want to avoid adding features that are simple to replicate in the other applications where people typically use Carbon.

Can you give me a better idea of what you want to use the headers/footers for?
