### ISSUE TITLE
Is there any version can deploy in local network?

### ISSUE THREAD

**Issue by stdinfo** [carbon-app/carbon#976]
Carbon is a really cool way to share code. We can use carbon.now.sh online normally, but it's not so convenient to use it in internal network(without internet). I would like to use it in a local network for some educational purpose and sharing code.
I trid to deploy it with code, but it seems useing many online resources. So is there any version I can deploy in a local network? 
If inconvenience, can you just tell me which files I need to modify? I'm not familiar with nodejs.
Thx bro.

**Comment by mfix22** [comment]
Hey @stdinfo, you can run the app locally by installing the files using `yarn`, and then running `npm build && npm start` — this will run the app on port 3000. 

As for which files to update, you just need to update [this one](https://github.com/carbon-app/carbon/blob/master/components/Meta.js), which loads the CodeMirror lib and themes from a CDN (`cdnjs`)

Let me know if you have other questions.

**Comment by stdinfo** [comment]
Thanks for replying, it works！
Besides `meta.js`, I also modified `font.js` and downloaded all font files.
And I noticed that there's no css file for theme named "a11y-dark", perhaps it should be remove from the theme list?
Another thing I'm a little confused is why it's always require `service-worker.js` which does not exist.

**Comment by mfix22** [comment]
Right! I forgot about `Font.js`. Thanks @stdinfo 

`a11y-dark` is still a valid theme, it just doesn't need a CSS file. The highlights config for it covers that theme.

`service-worker.js` is generated during out build [here](https://github.com/carbon-app/carbon/blob/master/next.config.js#L11). Once you run `yarn build`, it should be available in your output directory. 

Instead of loading `service-worker.js` from `/service-worker.js`, you might have to update the config to point to `/_next/static/service-worker.js` instead. This is handled for us in production [in our now.json](https://github.com/carbon-app/carbon/blob/master/now.json#L31).

**Comment by mfix22** [comment]
@stdinfo anything else I can answer for ya before closing this issue? 🙂

**Comment by stdinfo** [comment]
Ah, really appreciate for your helping! 
Actually, I have't set `service-worker` correctly yet(I changed the config but did't work.). But it seems has no affect on normal using.I think I'll try it myself latter.
If I have problem I'll open another issue.

**Comment by mfix22** [comment]
`service-worker` is used for when you want to use Carbon as a PWA, for offline use!
