### ISSUE TITLE
Use VS Code highlighting plugin

### ISSUE THREAD

**Issue by atomiks** [carbon-app/carbon#989]
### Expected Behavior

Themes should match their VS Code equivalents (very granular highlighting)

https://github.com/andrewbranch/gatsby-remark-vscode

### Actual Behavior

Theme highlighting lacks the necessary tokens to accurately match their original / VS Code themes.

**Comment by mfix22** [comment]
@atomiks would a solution like this, #990, work for you? 

I have attempted to add the missing tokens, and if there are any more, I will consider adding them as well. I would also be happy to accept a PR that improves the theme options/configs. 

Your proposed solution won't work for us, since Carbon doesn't use Gatsby. Do you know of a similar plugin for Codemirror (the library we use for syntax highlighting)?

**Comment by atomiks** [comment]
I am sure it helps but I don't think it's as complete as the VS Code textmate tokenization. 

Would you consider using Gatsby and that plugin (or taking a look at the way the plugin works and implement it standalone) just to take the screenshot? CodeMirror can still be used for typing/pasting code, but its colorization is so limited and you can't match themes correctly.

Actually, the best option would be using the Monaco editor with custom themes like CodeSandbox does in the browser.

**Comment by mfix22** [comment]
> Would you consider using Gatsby and that plugin (or taking a look at the way the plugin works and implement it standalone) just to take the screenshot

We would have to rewrite the entire application in order to use Gatsby, which is not an option we will consider.

Using a different editor _might_ be feasible, but I am not sure the wins will be worth the effort. 

I'll leave this open for further consideration.
